In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import os
import glob
import regex as re

In [2]:
# map drive to retrieve datasets
from google.colab import drive
drive.mount('/content/Drive')

# map drive to retrieve datasets
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).
Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).

In [3]:
# Import the data for inpection
gun_laws = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/gun_law_provisions_by_year_state.csv')
deaths_df = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/data-table.csv')

## Inspect gun law provisions by year (through 2020) and state.csv

In [4]:
#Count the non-null values
gun_laws.count()

state                           1500
year                            1500
felony                          1500
invcommitment                   1500
invoutpatient                   1500
                                ...
expartesurrendernoconditions    1500
expartesurrenderdating          1500
dvroremoval                     1500
stalking                        1500
lawtotal                        1500
Length: 137, dtype: int64

In [5]:
# Convert the columns into a list
gun_laws.columns.tolist()

['state',
 'year',
 'felony',
 'invcommitment',
 'invoutpatient',
 'danger',
 'drugmisdemeanor',
 'alctreatment',
 'alcoholism',
 'relinquishment',
 'violent',
 'violenth',
 'violentpartial',
 'dealer',
 'dealerh',
 'recordsall',
 'recordsallh',
 'recordsdealer',
 'recordsdealerh',
 'reportall',
 'reportallh',
 'reportdealer',
 'reportdealerh',
 'purge',
 'residential',
 'theft',
 'security',
 'inspection',
 'ammlicense',
 'ammrecords',
 'permit',
 'permith',
 'fingerprint',
 'training',
 'permitlaw',
 'registration',
 'registrationh',
 'defactoreg',
 'defactoregh',
 'ammpermit',
 'ammrestrict',
 'age21handgunsale',
 'age18longgunsale',
 'age21longgunsaled',
 'age21longgunsale',
 'age21handgunpossess',
 'age18longgunpossess',
 'age21longgunpossess',
 'loststolen',
 'amm18',
 'amm21h',
 'universal',
 'universalh',
 'gunshow',
 'gunshowh',
 'universalpermit',
 'universalpermith',
 'backgroundpurge',
 'ammbackground',
 'threedaylimit',
 'mentalhealth',
 'statechecks',
 'statechecksh',
 'waiting',
 'waitingh',
 'assault',
 'onefeature',
 'assaultlist',
 'assaultregister',
 'assaulttransfer',
 'magazine',
 'tenroundlimit',
 'magazinepreowned',
 'onepermonth',
 'traffickingbackground',
 'traffickingprohibited',
 'traffickingprohibitedh',
 'strawpurchase',
 'strawpurchaseh',
 'microstamp',
 'gvro',
 'gvrolawenforcement',
 'college',
 'collegeconcealed',
 'elementary',
 'opencarryh',
 'opencarryl',
 'opencarrypermith',
 'opencarrypermitl',
 'permitconcealed',
 'mayissue',
 'showing',
 'ccbackground',
 'ccbackgroundnics',
 'ccrenewbackground',
 'ccrevoke',
 'nosyg',
 'personalized',
 'lockd',
 'lockp',
 'locked',
 'lockstandards',
 'capliability',
 'capaccess',
 'capuses',
 'capunloaded',
 'cap18',
 'cap16',
 'cap14',
 'junkgun',
 'liability',
 'immunity',
 'preemption',
 'preemptionnarrow',
 'preemptionbroad',
 'mcdv',
 'mcdvdating',
 'mcdvsurrender',
 'mcdvsurrendernoconditions',
 'mcdvsurrenderdating',
 'mcdvremovalallowed',
 'mcdvremovalrequired',
 'incidentremoval',
 'incidentall',
 'dvro',
 'dvrodating',
 'exparte',
 'expartedating',
 'dvrosurrender',
 'dvrosurrendernoconditions',
 'dvrosurrenderdating',
 'expartesurrender',
 'expartesurrendernoconditions',
 'expartesurrenderdating',
 'dvroremoval',
 'stalking',
 'lawtotal']

In [6]:
# Check the data type of the year 
gun_laws['year'].dtypes

# Filter the dataset by years from 2013-2020
gun_laws = gun_laws[gun_laws['year'] >= 2013]

In [7]:
gun_laws.dtypes

state                           object
year                             int64
felony                           int64
invcommitment                    int64
invoutpatient                    int64
                                 ...
expartesurrendernoconditions     int64
expartesurrenderdating           int64
dvroremoval                      int64
stalking                         int64
lawtotal                         int64
Length: 137, dtype: object

In [8]:
gun_laws.tail(5)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
1495,Wyoming,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1496,Wyoming,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1497,Wyoming,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1498,Wyoming,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1499,Wyoming,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7

In [9]:
states = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}
gun_laws['state'] = gun_laws['state'].str.strip().replace(states)
gun_laws.sample(5)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
749,MO,2020,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2
653,MI,2014,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,20
89,AZ,2020,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,8
895,NJ,2016,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,67
1314,UT,2015,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11

**Inspect death rates**

In [10]:
deaths_df.count()

YEAR      400
STATE     400
RATE      400
DEATHS    400
URL       400
dtype: int64

In [11]:
deaths_df.columns.tolist()

['YEAR', 'STATE', 'RATE', 'DEATHS', 'URL']

In [12]:
deaths_df.sample(5)

,YEAR,STATE,RATE,DEATHS,URL
104,2018,CA,7.5,3040,/nchs/pressroom/states/california/ca.htm
177,2017,NV,16.7,508,/nchs/pressroom/states/nevada/nevada.htm
159,2017,GA,15.4,1623,/nchs/pressroom/states/georgia/georgia.htm
383,2005,ND,8.8,61,/nchs/pressroom/states/northdakota/northdakota...
176,2017,NE,8.3,160,/nchs/pressroom/states/nebraska/nebraska.htm

In [13]:
deaths_df = deaths_df.drop('URL', axis=1)
deaths_df

     YEAR STATE  RATE  DEATHS
0    2020    AL  23.6    1141
1    2020    AK  23.5     175
2    2020    AZ  16.7    1265
3    2020    AR  22.6     673
4    2020    CA   8.5    3449
..    ...   ...   ...     ...
395  2005    VA  11.5     888
396  2005    WA   8.8     567
397  2005    WV  13.8     261
398  2005    WI   8.5     474
399  2005    WY  13.4      71

[400 rows x 4 columns]

In [14]:
deaths_df = deaths_df.rename(columns={'YEAR': 'year', 'STATE': 'state', 'RATE': 'rate', 'DEATHS': 'deaths'})
deaths_df.sample(5)

     year state  rate  deaths
108  2018    FL  12.9    2902
106  2018    CT   4.9     186
324  2014    MO  15.3     943
71   2019    MI  12.1    1220
19   2020    MD  13.5     803

### Separate out deaths_df and gun_laws by year

In [15]:
merged_2015_deaths_df = deaths_df.loc[deaths_df['year'] == 2015]
merged_2016_deaths_df = deaths_df.loc[deaths_df['year'] == 2016]
merged_2017_deaths_df = deaths_df.loc[deaths_df['year'] == 2017]
merged_2018_deaths_df = deaths_df.loc[deaths_df['year'] == 2018]
merged_2019_deaths_df = deaths_df.loc[deaths_df['year'] == 2019]
merged_2020_deaths_df = deaths_df.loc[deaths_df['year'] == 2020]

In [16]:
gun_laws_2015_df = gun_laws.loc[gun_laws['year'] == 2015]
gun_laws_2016_df = gun_laws.loc[gun_laws['year'] == 2016]
gun_laws_2017_df = gun_laws.loc[gun_laws['year'] == 2017]
gun_laws_2018_df = gun_laws.loc[gun_laws['year'] == 2018]
gun_laws_2019_df = gun_laws.loc[gun_laws['year'] == 2019]
gun_laws_2020_df = gun_laws.loc[gun_laws['year'] == 2020]

In [17]:
gun_laws_2018_df.head()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
27,AL,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
57,AK,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
87,AZ,2018,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,8
117,AR,2018,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
147,CA,2018,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,109

## Merge deaths_df and gun_laws datasets by year

In [18]:
merged_law_deaths_2015 = pd.merge(gun_laws_2015_df, merged_2015_deaths_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_deaths_2016 = pd.merge(gun_laws_2016_df, merged_2016_deaths_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_deaths_2017 = pd.merge(gun_laws_2017_df, merged_2017_deaths_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_deaths_2018 = pd.merge(gun_laws_2018_df, merged_2018_deaths_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_deaths_2019 = pd.merge(gun_laws_2019_df, merged_2019_deaths_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_deaths_2020 = pd.merge(gun_laws_2020_df, merged_2020_deaths_df, how='inner', left_on=['state'], right_on=['state'])

In [19]:
merged_law_deaths_2020.head()

,state,year_x,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,year_y,rate,deaths
0,AL,2020,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,10,2020,23.6,1141
1,AK,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,2020,23.5,175
2,AZ,2020,1,1,1,1,0,0,0,0,...,0,0,0,0,0,1,8,2020,16.7,1265
3,AR,2020,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,11,2020,22.6,673
4,CA,2020,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,111,2020,8.5,3449

In [22]:
merged_law_deaths_2015.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2015.csv', index=False)

In [23]:
merged_law_deaths_2016.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2016.csv', index=False)

In [24]:
merged_law_deaths_2017.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2017.csv', index=False)

In [25]:
merged_law_deaths_2018.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2018.csv', index=False)

In [26]:
merged_law_deaths_2019.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2019.csv', index=False)

In [27]:
merged_law_deaths_2020.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_deaths_2020.csv', index=False)

In [21]:
merged_law_deaths_2018.head()

,state,year_x,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,year_y,rate,deaths
0,AL,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,10,2018,21.8,1064
1,AK,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,2018,21.0,155
2,AZ,2018,1,1,1,1,0,0,0,0,...,0,0,0,0,0,1,8,2018,15.3,1147
3,AR,2018,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,11,2018,18.9,573
4,CA,2018,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,109,2018,7.5,3040

## Merge all back into one dataset

In [32]:
# setting the path for joining multiple files
files = os.path.join('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged*.csv')

# list of merged files returned
files = glob.glob(files)

# joining files with concat and read_csv
merged_df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [33]:
merged_df.head()

,state,year_x,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,year_y,rate,deaths
0,AL,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,10,2015,19.6,958
1,AK,2015,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,2015,23.4,177
2,AZ,2015,1,1,1,1,0,0,0,0,...,0,0,0,0,0,1,8,2015,13.8,970
3,AR,2015,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,11,2015,16.9,520
4,CA,2015,1,1,0,1,0,0,1,0,...,1,1,1,1,1,1,102,2015,7.7,3095

In [34]:
merged_df.tail()

,state,year_x,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,year_y,rate,deaths
295,VA,2020,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,25,2020,13.4,1174
296,WA,2020,1,1,1,1,0,0,0,0,...,1,1,0,1,0,0,55,2020,10.9,864
297,WV,2020,1,1,1,1,0,0,1,0,...,0,0,0,0,0,0,18,2020,18.1,325
298,WI,2020,1,1,1,1,0,1,0,0,...,1,0,0,0,0,1,23,2020,12.2,717
299,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,2020,25.9,154

In [35]:
# merge state and year into one column, replace as index and drop 'year' and 'state' columns
merged_df["state_year"] = merged_df['state'] +"_"+ merged_df['year_x'].astype(str)
merged_df.drop(['year_x','year_y','state'], axis=1, inplace=True)
merged_df.sample(5)

,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,violent,violenth,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,rate,deaths,state_year
49,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,8,19.6,113,WY_2015
128,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,9,10.4,146,NH_2017
258,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,30,13.7,3041,FL_2020
107,1,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,39,11.7,111,DE_2017
193,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,15,13.2,397,UT_2018

In [36]:
# find data
merged_df.deaths.describe()

count     300.000000
mean      795.306667
std       766.145811
min        37.000000
25%       212.000000
50%       595.000000
75%      1094.000000
max      4164.000000
Name: deaths, dtype: float64

In [37]:
# splitting death rate by above and below national mean

merged_df['deaths_above_below_mean'] = np.where(deaths_df['deaths'] < 795, 'below_national_mean', 'above_national_mean')
merged_df.head(5)

,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,violent,violenth,...,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,rate,deaths,state_year,deaths_above_below_mean
0,0,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,10,19.6,958,AL_2015,above_national_mean
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,23.4,177,AK_2015,below_national_mean
2,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,1,8,13.8,970,AZ_2015,above_national_mean
3,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,11,16.9,520,AR_2015,below_national_mean
4,1,1,0,1,0,0,1,0,1,1,...,1,1,1,1,1,102,7.7,3095,CA_2015,above_national_mean

In [44]:
merged_df = merged_df.reindex(columns=['state_year', 'lawtotal', 'rate', 'deaths', 'deaths_above_below_mean'])
merged_df

    state_year  lawtotal  rate  deaths deaths_above_below_mean
0      AL_2015        10  19.6     958     above_national_mean
1      AK_2015         3  23.4     177     below_national_mean
2      AZ_2015         8  13.8     970     above_national_mean
3      AR_2015        11  16.9     520     below_national_mean
4      CA_2015       102   7.7    3095     above_national_mean
..         ...       ...   ...     ...                     ...
295    VA_2020        25  13.4    1174     above_national_mean
296    WA_2020        55  10.9     864     above_national_mean
297    WV_2020        18  18.1     325     below_national_mean
298    WI_2020        23  12.2     717     below_national_mean
299    WY_2020         7  25.9     154     below_national_mean

[300 rows x 5 columns]

In [45]:
# Export the final dataset
merged_df.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/merged_df.csv', index=False)
merged_df.to_json('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/merged_df.json')