In [ ]:
# Import Dependencies
import pandas as pd
import numpy as np
import os
import glob

In [ ]:
# map drive to retrieve datasets
from google.colab import drive
drive.mount('/content/Drive')

Mounted at /content/Drive

In [ ]:
# map drive to retrieve datasets
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).

In [ ]:
# Import the data for inpection
accidental_deaths = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/accidental_deaths_2018_2022.csv')
gun_data = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/Gun_Data_Codebook_and_OLS_Regression_Outputs_Gun_Data.csv')
gun_laws = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/gun_law_provisions_by_year_state.csv')
gun_violence_2013_2018 = pd.read_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/Resources/gun_violence_data_01_2013_03_2018.csv')

## Clean the Accidental Deaths 2018 - 2022 CSV file

In [ ]:
# Look at the columns of accidental_deaths
accidental_deaths.count()

Incident ID       2000
Incident Date     2000
State             2000
City Or County    2000
Address           1898
# Killed          2000
# Injured         2000
Operations           0
dtype: int64

In [ ]:
# Inspect the data in the Incident Date column
accidental_deaths['Incident Date'].head(5)

0    October 21, 2022
1    October 19, 2022
2    October 19, 2022
3    October 19, 2022
4    October 18, 2022
Name: Incident Date, dtype: object

In [ ]:
# Splitting the Incident Date column into three separate columns
accidental_deaths[['month', 'day', 'date']] = accidental_deaths['Incident Date'].str.split(" ", expand=True)

In [ ]:
# Confirm the values of the date columns
accidental_deaths['date'].head(5)

0    2022
1    2022
2    2022
3    2022
4    2022
Name: date, dtype: object

In [ ]:
# Rename the date column to year
accidental_deaths.rename(columns={'Incident ID':'incident_id', "State":'state', '# Killed':'deaths', '# Injured':'injuries', 'date':'year'}, inplace=True)

In [ ]:
accidental_deaths = accidental_deaths.drop(['Operations', 'Address', 'Incident Date', 'month', 'day', 'City Or County'], axis=1)

In [ ]:
accidental_deaths = accidental_deaths.sort_values(['year'], ascending = True)
accidental_deaths.sample(5)

      incident_id       state  deaths  injuries  year
903       1927638     Georgia       1         0  2020
435       2289434        Ohio       1         0  2021
1683      1457269  New Jersey       1         0  2019
1313      1669964    Missouri       1         0  2020
1094      1772221  New Jersey       1         0  2020

In [ ]:
year = accidental_deaths['year']
accidental_deaths.drop(labels=['year'], axis=1, inplace=True)
accidental_deaths.insert(1, 'year', year)
accidental_deaths.sample(5)

      incident_id  year           state  deaths  injuries
430       2163895  2021           Texas       1         0
1057      1795177  2020        Illinois       1         0
1868      1306941  2019  South Carolina       1         0
193       2364342  2022            Ohio       1         0
403       2175762  2021       Minnesota       1         0

In [ ]:
accidental_df = accidental_deaths
accidental_df.to_csv('/content/Drive/MyDrive/Final_Project//segment_2_machine_learning/Cleaning_ML/cleaned/cleaned_accidental_df.csv', index=False)

## Gun Violence Data

In [ ]:
# Review all columns
gun_violence_2013_2018.columns.tolist()

['incident_id',
 'date',
 'state',
 'city_or_county',
 'address',
 'n_killed',
 'n_injured',
 'incident_url',
 'source_url',
 'incident_url_fields_missing',
 'congressional_district',
 'gun_stolen',
 'gun_type',
 'incident_characteristics',
 'latitude',
 'location_description',
 'longitude',
 'n_guns_involved',
 'notes',
 'participant_age',
 'participant_age_group',
 'participant_gender',
 'participant_name',
 'participant_relationship',
 'participant_status',
 'participant_type',
 'sources',
 'state_house_district',
 'state_senate_district']

In [ ]:
# split the date column into separate columns for date, day, month
# replace date with year
gun_violence_2013_2018[['date', 'month', 'day']] = gun_violence_2013_2018.date.str.split("-", expand=True)
gun_violence_2013_2018.columns = gun_violence_2013_2018.columns.str.replace('date', 'year')

In [ ]:
# Create a new dataframe for latitude and longitude
location = gun_violence_2013_2018[['latitude','longitude']].copy()

In [ ]:
# Drop unneeded columns
gun_violence_cleaned = gun_violence_2013_2018.drop(['city_or_county','address','incident_url',
                                                    'source_url','incident_url_fields_missing','congressional_district',
                                                    'gun_stolen','gun_type','incident_characteristics',
                                                    'location_description','n_guns_involved',
                                                     'notes','participant_age','participant_age_group',
                                                     'participant_gender','participant_name','participant_relationship',
                                                     'participant_status','participant_type','sources',
                                                     'state_house_district','state_senate_district','month','day','latitude','longitude'], axis=1)

In [ ]:
# Rename the date column to year
gun_violence_cleaned.rename(columns={'n_killed':'deaths', 'n_injured':'injuries'}, inplace=True)

In [ ]:
gun_violence_cleaned.sample(5)

        incident_id  year           state  deaths  injuries
215824       975500  2017        Kentucky       0         1
127539       568432  2016  North Carolina       0         0
27180        161735  2014         Alabama       1         2
150214       675145  2016  South Carolina       0         0
70452        341766  2015   Massachusetts       0         0

In [ ]:
gun_violence_cleaned.dtypes
gun_violence_cleaned['year'] = pd.to_numeric(gun_violence_cleaned['year'])

In [ ]:
gun_violence_cleaned.to_csv('/content/Drive/MyDrive/Final_Project//segment_2_machine_learning/Cleaning_ML/cleaned/cleaned_gun_violence.csv', index=False)

## Inspect gun law provisions by year (through 2020) and state.csv

In [ ]:
#Count the non-null values
gun_laws.count()

state                           1500
year                            1500
felony                          1500
invcommitment                   1500
invoutpatient                   1500
                                ...
expartesurrendernoconditions    1500
expartesurrenderdating          1500
dvroremoval                     1500
stalking                        1500
lawtotal                        1500
Length: 137, dtype: int64

In [ ]:
# Convert the columns into a list
gun_laws.columns.tolist()

['state',
 'year',
 'felony',
 'invcommitment',
 'invoutpatient',
 'danger',
 'drugmisdemeanor',
 'alctreatment',
 'alcoholism',
 'relinquishment',
 'violent',
 'violenth',
 'violentpartial',
 'dealer',
 'dealerh',
 'recordsall',
 'recordsallh',
 'recordsdealer',
 'recordsdealerh',
 'reportall',
 'reportallh',
 'reportdealer',
 'reportdealerh',
 'purge',
 'residential',
 'theft',
 'security',
 'inspection',
 'ammlicense',
 'ammrecords',
 'permit',
 'permith',
 'fingerprint',
 'training',
 'permitlaw',
 'registration',
 'registrationh',
 'defactoreg',
 'defactoregh',
 'ammpermit',
 'ammrestrict',
 'age21handgunsale',
 'age18longgunsale',
 'age21longgunsaled',
 'age21longgunsale',
 'age21handgunpossess',
 'age18longgunpossess',
 'age21longgunpossess',
 'loststolen',
 'amm18',
 'amm21h',
 'universal',
 'universalh',
 'gunshow',
 'gunshowh',
 'universalpermit',
 'universalpermith',
 'backgroundpurge',
 'ammbackground',
 'threedaylimit',
 'mentalhealth',
 'statechecks',
 'statechecksh',
 'waiting',
 'waitingh',
 'assault',
 'onefeature',
 'assaultlist',
 'assaultregister',
 'assaulttransfer',
 'magazine',
 'tenroundlimit',
 'magazinepreowned',
 'onepermonth',
 'traffickingbackground',
 'traffickingprohibited',
 'traffickingprohibitedh',
 'strawpurchase',
 'strawpurchaseh',
 'microstamp',
 'gvro',
 'gvrolawenforcement',
 'college',
 'collegeconcealed',
 'elementary',
 'opencarryh',
 'opencarryl',
 'opencarrypermith',
 'opencarrypermitl',
 'permitconcealed',
 'mayissue',
 'showing',
 'ccbackground',
 'ccbackgroundnics',
 'ccrenewbackground',
 'ccrevoke',
 'nosyg',
 'personalized',
 'lockd',
 'lockp',
 'locked',
 'lockstandards',
 'capliability',
 'capaccess',
 'capuses',
 'capunloaded',
 'cap18',
 'cap16',
 'cap14',
 'junkgun',
 'liability',
 'immunity',
 'preemption',
 'preemptionnarrow',
 'preemptionbroad',
 'mcdv',
 'mcdvdating',
 'mcdvsurrender',
 'mcdvsurrendernoconditions',
 'mcdvsurrenderdating',
 'mcdvremovalallowed',
 'mcdvremovalrequired',
 'incidentremoval',
 'incidentall',
 'dvro',
 'dvrodating',
 'exparte',
 'expartedating',
 'dvrosurrender',
 'dvrosurrendernoconditions',
 'dvrosurrenderdating',
 'expartesurrender',
 'expartesurrendernoconditions',
 'expartesurrenderdating',
 'dvroremoval',
 'stalking',
 'lawtotal']

In [ ]:
# Check the data type of the year 
gun_laws['year'].dtypes

# Filter the dataset by years from 2013-2020
gun_laws = gun_laws[gun_laws['year'] >= 2013]

In [ ]:
gun_laws.dtypes

state                           object
year                             int64
felony                           int64
invcommitment                    int64
invoutpatient                    int64
                                 ...
expartesurrendernoconditions     int64
expartesurrenderdating           int64
dvroremoval                      int64
stalking                         int64
lawtotal                         int64
Length: 137, dtype: object

In [ ]:
gun_laws.tail(5)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
1495,Wyoming,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1496,Wyoming,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1497,Wyoming,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1498,Wyoming,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1499,Wyoming,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7

## Merging cleaned incidents

In [ ]:
# setting the path for joining multiple files
files = os.path.join('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/cleaned/cleaned*.csv')

# list of merged files returned
files = glob.glob(files)

# joining files with concat and read_csv
merged_yearly_incidents_df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [ ]:
merged_yearly_incidents_df.head(5)

   incident_id  year           state  deaths  injuries
0      1227183  2018           Texas       1         0
1      1258777  2018        Colorado       1         4
2      1228741  2018            Ohio       1         0
3      1228092  2018        Virginia       1         0
4      1229736  2018  North Carolina       1         0

In [ ]:
merged_yearly_incidents_df = merged_yearly_incidents_df.sort_values(['year','state'], ascending = True)
merged_yearly_incidents_df.head(5)

      incident_id  year    state  deaths  injuries
2127       490395  2013  Alabama       0         4
2272       496668  2013  Alabama       3         5
2051       484307  2013  Arizona       2         4
2072       486153  2013  Arizona       0         5
2215       480897  2013  Arizona       0         4

In [ ]:
# Filter the dataset by years from 2013-2020 to match gun laws datasheet
merged_yearly_incidents_df = merged_yearly_incidents_df[merged_yearly_incidents_df['year'] <= 2020]
merged_yearly_incidents_df.tail(5)

      incident_id  year      state  deaths  injuries
932       1750067  2020  Wisconsin       1         0
935       1742026  2020  Wisconsin       1         0
1064      1775315  2020  Wisconsin       1         0
1089      1767974  2020  Wisconsin       1         0
739       1862872  2020    Wyoming       1         0

In [ ]:
merged_yearly_incidents_df.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/cleaned/merged_yearly_incidents_df.csv', index=False)

### Separate out merged_yearly_incidents_df and gun_laws by year

In [ ]:
merged_2013_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2013]
merged_2013_incidents_df.head(5)

      incident_id  year    state  deaths  injuries
2127       490395  2013  Alabama       0         4
2272       496668  2013  Alabama       3         5
2051       484307  2013  Arizona       2         4
2072       486153  2013  Arizona       0         5
2215       480897  2013  Arizona       0         4

In [ ]:
merged_2014_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2014]
merged_2015_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2015]
merged_2016_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2016]
merged_2017_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2017]
merged_2018_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2018]
merged_2019_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2019]
merged_2020_incidents_df = merged_yearly_incidents_df.loc[merged_yearly_incidents_df['year'] == 2020]

In [ ]:
gun_laws_2013_df = gun_laws.loc[gun_laws['year'] == 2013]
gun_laws_2013_df.head(5)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
22,Alabama,2013,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
52,Alaska,2013,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
82,Arizona,2013,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,8
112,Arkansas,2013,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
142,California,2013,1,1,0,1,0,0,1,0,...,1,1,1,1,1,1,1,1,1,99

In [ ]:
gun_laws_2014_df = gun_laws.loc[gun_laws['year'] == 2014]
gun_laws_2015_df = gun_laws.loc[gun_laws['year'] == 2015]
gun_laws_2016_df = gun_laws.loc[gun_laws['year'] == 2016]
gun_laws_2017_df = gun_laws.loc[gun_laws['year'] == 2017]
gun_laws_2018_df = gun_laws.loc[gun_laws['year'] == 2018]
gun_laws_2019_df = gun_laws.loc[gun_laws['year'] == 2019]
gun_laws_2020_df = gun_laws.loc[gun_laws['year'] == 2020]

In [ ]:
gun_laws_2018_df.head()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
27,Alabama,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
57,Alaska,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
87,Arizona,2018,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,8
117,Arkansas,2018,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
147,California,2018,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,109

### Merge incidents by state

In [ ]:
merged_2013_incidents_df = merged_2013_incidents_df.groupby(['state']).sum()
merged_2013_incidents_df = merged_2013_incidents_df.drop(['incident_id','year'], axis=1)
merged_2013_incidents_df.head(5)

             deaths  injuries
state
Alabama           3         9
Arizona           8        16
California       46       139
Colorado          4         9
Connecticut       2        13

In [ ]:
merged_2014_incidents_df = merged_2014_incidents_df.groupby(['state']).sum()
merged_2014_incidents_df = merged_2014_incidents_df.drop(['incident_id','year'], axis=1)
merged_2015_incidents_df = merged_2015_incidents_df.groupby(['state']).sum()
merged_2015_incidents_df = merged_2015_incidents_df.drop(['incident_id','year'], axis=1)
merged_2016_incidents_df = merged_2016_incidents_df.groupby(['state']).sum()
merged_2016_incidents_df = merged_2016_incidents_df.drop(['incident_id','year'], axis=1)
merged_2017_incidents_df = merged_2017_incidents_df.groupby(['state']).sum()
merged_2017_incidents_df = merged_2017_incidents_df.drop(['incident_id','year'], axis=1)
merged_2018_incidents_df = merged_2018_incidents_df.groupby(['state']).sum()
merged_2018_incidents_df = merged_2018_incidents_df.drop(['incident_id','year'], axis=1)
merged_2019_incidents_df = merged_2019_incidents_df.groupby(['state']).sum()
merged_2019_incidents_df = merged_2019_incidents_df.drop(['incident_id','year'], axis=1)
merged_2020_incidents_df = merged_2020_incidents_df.groupby(['state']).sum()
merged_2020_incidents_df = merged_2020_incidents_df.drop(['incident_id','year'], axis=1)

## Merge merged_yearly_incidents_df and gun_laws datasets by year

In [ ]:
merged_law_incidents_2013 = pd.merge(gun_laws_2013_df, merged_2013_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2014 = pd.merge(gun_laws_2014_df, merged_2014_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2015 = pd.merge(gun_laws_2015_df, merged_2015_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2016 = pd.merge(gun_laws_2016_df, merged_2016_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2017 = pd.merge(gun_laws_2017_df, merged_2017_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2018 = pd.merge(gun_laws_2018_df, merged_2018_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2019 = pd.merge(gun_laws_2019_df, merged_2019_incidents_df, how='inner', left_on=['state'], right_on=['state'])
merged_law_incidents_2020 = pd.merge(gun_laws_2020_df, merged_2020_incidents_df, how='inner', left_on=['state'], right_on=['state'])

In [ ]:
merged_law_incidents_2020.head()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries
0,Alabama,2020,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,19,6
1,Alaska,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,1,0
2,Arizona,2020,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,1,8,12,0
3,Arkansas,2020,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,11,6,1
4,California,2020,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,1,111,19,6

In [ ]:
merged_law_incidents_2013.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2013.csv', index=False)
merged_law_incidents_2014.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2014.csv', index=False)
merged_law_incidents_2015.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2015.csv', index=False)
merged_law_incidents_2016.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2016.csv', index=False)
merged_law_incidents_2017.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2017.csv', index=False)
merged_law_incidents_2018.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2018.csv', index=False)
merged_law_incidents_2019.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2019.csv', index=False)
merged_law_incidents_2020.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged_law_incidents_2020.csv', index=False)

In [ ]:
merged_law_incidents_2018.head()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries
0,Alabama,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,140,219
1,Alaska,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,11,19
2,Arizona,2018,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,1,8,86,73
3,Arkansas,2018,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,11,47,83
4,California,2018,1,1,0,1,0,0,1,1,...,1,1,1,1,1,1,1,109,306,432

## Merge all back into one dataset

In [ ]:
# setting the path for joining multiple files
files = os.path.join('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/to_merge/merged*.csv')

# list of merged files returned
files = glob.glob(files)

# joining files with concat and read_csv
merged_yearly_incidents_df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [ ]:
merged_yearly_incidents_df.head()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries
0,Alabama,2013,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,10,3,9
1,Arizona,2013,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,1,8,8,16
2,California,2013,1,1,0,1,0,0,1,0,...,1,1,1,1,1,1,1,99,46,139
3,Colorado,2013,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,30,4,9
4,Connecticut,2013,1,1,1,1,1,0,0,1,...,1,1,0,0,0,0,1,82,2,13

In [ ]:
merged_yearly_incidents_df.tail()

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries
368,Virginia,2020,1,1,1,1,0,0,0,0,...,1,0,0,0,0,0,0,25,18,0
369,Washington,2020,1,1,1,1,0,0,0,0,...,0,1,1,0,1,0,0,55,6,8
370,West Virginia,2020,1,1,1,1,0,0,1,0,...,0,0,0,0,0,0,0,18,4,1
371,Wisconsin,2020,1,1,1,1,0,1,0,0,...,1,1,0,0,0,0,1,23,9,0
372,Wyoming,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,1,0

In [ ]:
# merge state and year into one column, replace as index and drop 'year' and 'state' columns
merged_yearly_incidents_df["state_year"] = merged_yearly_incidents_df['state'] +"_"+ merged_yearly_incidents_df['year'].astype(str)
merged_yearly_incidents_df.drop(['year','state'], axis=1, inplace=True)
merged_yearly_incidents_df.sample(5)

,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,violent,violenth,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries,state_year
45,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,6,522,817,Georgia_2014
46,1,1,1,1,1,1,0,1,1,1,...,1,1,1,1,0,0,78,8,13,Hawaii_2014
307,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,22,7,Mississippi_2019
313,1,1,1,1,1,0,0,1,0,0,...,1,1,1,1,0,1,77,12,1,New York_2019
333,1,1,0,1,0,0,1,1,1,1,...,1,1,1,1,1,1,111,19,6,California_2020

In [ ]:
# find data
merged_yearly_incidents_df.deaths.describe()

count     373.000000
mean      163.959786
std       252.064851
min         0.000000
25%        11.000000
50%        47.000000
75%       220.000000
max      1423.000000
Name: deaths, dtype: float64

In [ ]:
# splitting death rate by above and below national mean

merged_yearly_incidents_df['deaths_above_below_mean'] = np.where(merged_yearly_incidents_df['deaths'] < 164, 'below_national_mean', 'above_national_mean')
merged_yearly_incidents_df.head(5)

,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,violent,violenth,...,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,deaths,injuries,state_year,deaths_above_below_mean
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,10,3,9,Alabama_2013,below_national_mean
1,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,1,8,8,16,Arizona_2013,below_national_mean
2,1,1,0,1,0,0,1,0,1,1,...,1,1,1,1,1,99,46,139,California_2013,below_national_mean
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,30,4,9,Colorado_2013,below_national_mean
4,1,1,1,1,1,0,0,1,1,1,...,0,0,0,0,1,82,2,13,Connecticut_2013,below_national_mean

In [ ]:
# Export the final dataset
merged_yearly_incidents_df.to_csv('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/law_inc_df.csv', index=False)
merged_yearly_incidents_df.to_json('/content/Drive/MyDrive/Final_Project/segment_2_machine_learning/Cleaning_ML/law_inc_df.json')